spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/postgres?schema=ws
    username: jefao
    password: jefao123
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
server:
  error:
    include-message: always