version: "3"
services:
  db-websocket:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=jefao123
      - MYSQL_USER=jefao
      - MYSQL_PASSWORD=jefao
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - 3306:3306